### ISSUE TITLE
Bring back number of reviews?

### ISSUE THREAD

**Issue by Makstuff** [Cside/return-amazon-5-stars-and-number-of-reviews#17]
Since along with the stars, amazon also removed the number of reviews from the product overview, it would be nice if you could bring back these numbers too. No idea if this is even possible, but it would make browsing much more convenient.

**Comment by Cside** [comment]
@Cimiteriophiliac 
Hi,
I have added the function to bring the number of reviews back in the latest version (0.3.2).
It will be updated automatically within a few hours.

Thank you for your valuable feedback.
