### ISSUE TITLE
Bring back access to full review set

### ISSUE THREAD

**Issue by knp2193** [Cside/return-amazon-5-stars-and-number-of-reviews#18]
Along with the changes to the rating, amazon also changed the way we view reviews. 

It only allows me to view 100 reviews per filter, instead of allowing me to keep paginating next. It blocks me after 10 pages.

**Comment by Cside** [comment]
I did some research and found that it was technically impossible to get reviews after page 11.
I am sorry, but I cannot implement your request.

Thank you for your valuable opinion.
